### ISSUE TITLE
Image for readme

### ISSUE THREAD

**Issue by fxg42** [fxg42/phoenix-flux-react#1]
![elixir - 4](https://cloud.githubusercontent.com/assets/425363/6131715/de297278-b11b-11e4-8080-815ef5d650c2.png)

**Comment by abitdodgy** [comment]
@fxg42 how did you make the image? What tool did you use? It looks nice!

**Comment by fxg42** [comment]
@abitdodgy It's made with "Paper": https://www.fiftythree.com/

**Comment by abitdodgy** [comment]
@fxg42 thanks!
